### PR TITLE
feat: add history links

### LINKED ISSUE #10: Add ability to link to a specific history item
Captura de pantalla 2023-06-19 a las 15 31 08

I'd love to share the update above on Slack, Mastodon, etc. Would be cool to add a way to link to it.

### PR DESCRIPTION
**Pull request by koukama**
Fixes #10

### CODE REVIEW

**Comment by fmvilas** [comment]
Nice! Thanks for contributing! 🙌 Please check the log: https://app.netlify.com/sites/sunny-llama-069637/deploys/64a7cd3fb61874000851b796. In your local environment, you can run `npm run lint` to see the errors and fix them.

**Comment by fmvilas** [comment]
🤔 I was expecting that this link would take me to the history item in question but it's only taking me to the cycle page. For instance, it's taking me to `http://localhost:3001/projects/org/asyncapi/16/cycles/e4232524` but I was expecting it to take me to something like `http://localhost:3001/projects/org/asyncapi/16/cycles/e4232524#id-of-the-comment-here`. It would scroll down to the comment to make it visible and even highlight it.

A good example is what GitHub does when you click on the other icon you added (the chat bubble). It takes you to a specific comment and highlights it. Does that make sense?

**Comment by Amzani** [comment]
@koukama this is an example https://github.com/asyncapi/studio/issues/623#issuecomment-1575078396

**Review by Amzani — APPROVED** [review]
Great PR @koukama 
I see that you also highlight the comment
Screenshot 2023-07-13 at 16 29 50

LGTM

**Comment by fmvilas** [comment]
I only have one small request. These link and comment icons look out of place so what about placing them on the right side, at the same height of the "Updated progress of ..." text and with a smaller size? You know what I mean?

**Comment by koukama** [comment]
Screenshot 2023-07-14 at 09 30 42

how about this @fmvilas ?

**Comment by fmvilas** [comment]
That looks perfect @koukama 🙌

**Pull request merged**
